[general]
import = [
    # from https://github.com/alacritty/alacritty-theme
    "~/.config/alacritty/alacritty-theme/themes/gnome_terminal.toml"
]

[font]
size = 8.0

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "0xProto Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Off"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[selection]
save_to_clipboard = true
