#!/bin/sh
# The commands to run when starting window managers.
#
# obs.: With the `pidof` checks, this file should be safe to be executed multiple times
# without restaring multiple copies of the same processes.
#
# set xdg home locally, if not already set externally
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"

# shared terminal configs and colourschemes
[ -f "$XDG_CONFIG_HOME/xres/settings" ] && xrdb "$XDG_CONFIG_HOME/xres/settings"
[ -f "$XDG_CONFIG_HOME/xresources-term" ] && xrdb -merge "$XDG_CONFIG_HOME/xresources-term"
[ -f "$XDG_CONFIG_HOME/xresources-dwm" ] && xrdb -merge "$XDG_CONFIG_HOME/xresources-dwm"

# set the background wallpaper or solid color
if [ -f "$XDG_CONFIG_HOME/wallpaper" ]
then
    xwallpaper --zoom "$XDG_CONFIG_HOME/wallpaper"
else
    xsetroot -solid #140420
fi

# enable compositing
if ! pidof -x picom > /dev/null
then
    picom --daemon
fi

# associate keyboard and mouse events in X with commands
if ! pidof -x xbindkeys > /dev/null
then
    xbindkeys --file "$XDG_CONFIG_HOME/xres/xbindkeysrc"
fi

# hide the cursor after a period of inactivity
if ! pidof -x unclutter > /dev/null
then
    unclutter --timeout 10 &
fi

# synchronize Xorg's primary and clipboard selections
if ! pidof -x autocutsel > /dev/null
then
    autocutsel -s CLIPBOARD &
fi

# notifications daemon
if ! pidof -x dunst > /dev/null
then
    dunst &
fi

# screensaver, screen locker, and display power -- configs in `~/.xscreensaver`
if ! pidof -x xscreensaver > /dev/null
then
    xscreensaver --no-splash &
fi

# enable left pointer as the cursor
xsetroot -cursor_name left_ptr

# change the screen's color temperature -- configs in `~/.config/redshift.conf`
if ! pidof -x redshift > /dev/null
then
    redshift &
fi

# configure auto-repeat delay, rate, and which keys should repeat when held down
. $HOME/.local/scripts/configure-autorepeat.sh &
