#!/bin/sh
# Usage:
#   dmenu_run_xres [PROMPT]

PROMPT="${1:-Run this}"
FONT="$(xrdb -query | grep 'dmenu.font' | cut -d '	' -f 2)"
NF="$(xrdb -query | grep 'dmenu.nf' | cut -d '	' -f 2)"
NB="$(xrdb -query | grep 'dmenu.nb' | cut -d '	' -f 2)"
SF="$(xrdb -query | grep 'dmenu.sf' | cut -d '	' -f 2)"
SB="$(xrdb -query | grep 'dmenu.sb' | cut -d '	' -f 2)"

if [ -z "$NF" ] || [ -z "$NB" ] || [ -z "$SF" ] || [ -z "$SB" ] || [ -z "$FONT" ]
then
    dmenu_run -i -p "$PROMPT"
else
    dmenu_run -i -nb "$NB" -nf "$NF" -sb "$SB" -sf "$SF" -fn "$FONT" -p "$PROMPT"
fi
