#!/bin/sh
# Open all images with sxiv
# USAGE:
#   imgs [PATH]
#
# PATH Defaults to `pwd`
if [ "$#" -eq 0 ]
then
    ROOT_DIR="$(pwd)"
else
    ROOT_DIR="$1"
fi

find "$ROOT_DIR" -maxdepth 1 -type f -iregex '.*\(bmp\|gif\|jpe?g\|png\)$' | sort | nsxiv -ipqt > /dev/null 2>&1
