#!/bin/bash
# A simple dmenu script to lock/close the WM or to shutdown.
# Usage:
#   manage_session
OPTIONS='Lock screen
Close DWM
Reboot
Power-off'

option=$(echo "$OPTIONS" | dmenu_xres 'What now, chief?')
case "$option" in
    'Lock screen')
        xscreensaver-command --lock;;
    'Close DWM')
        pkill -x dwm;;
    'Reboot')
        pkill -x dwm
        reboot;;
    'Power-off')
        pkill -x dwm
        poweroff;;
esac
