#!/bin/bash
# A simple dmenu script to lock/close the WM or to shutdown.
# Usage:
#   manage_session
OPTIONS='Lock screen
Close BSPWM
Reboot
Power-off'

option=$(echo "$OPTIONS" | ,dmenu-xres 'What now, chief?')
case "$option" in
    'Lock screen')
        xscreensaver-command --lock;;
    'Close BSPWM')
        pkill -x polybar
        bspc quit;;
    'Reboot')
        pkill -x polbar
        bspc quit
        reboot;;
    'Power-off')
        pkill -x polbar
        bspc quit
        poweroff;;
esac
