#!/bin/sh
# Set the given image as the wallpaper
# USAGE
#   setxbackground IMAGE_PATH

# Print message to desktop notification or stdin
notify() {
    pidof -x dunst > /dev/null && dunstify "Background changed" "$1" || echo "Changed the background to '$1'"
}

if [ "$#" -ne 1 ]
then
    echo "Error: expected a single argument (the path to an image file) but received $#. Aborting."
    echo "Usage:"
    echo "    ,setxbackground FILE"
    exit 1
fi

IMAGE_PATH="${XDG_CONFIG_HOME:-"$HOME/.config"}/wallpaper"
cp "$1" "$IMAGE_PATH" && hsetroot -cover "$IMAGE_PATH"
notify "$1"
