#!/bin/sh
# A simple script to quickly change between Xresources colourschemes

# Print message to desktop notification or stdin
notify() {
    pgrep dunst 1> /dev/null && dunstify "Colourscheme loaded" "$1" || echo "Loaded the '$1' colourscheme"
}

THEMES_DIR="$XDG_CONFIG_HOME/xres/dwm-themes"
fname=$(find "$THEMES_DIR" -printf '%f\n' | sort | ,dmenu_xres 'Which colourscheme?')

if [ ! -f "$THEMES_DIR/$fname" ]; then
    echo "Invalid '$fname' theme, doing nothing..."
    exit 1
fi

cp "$THEMES_DIR/$fname" ~/.config/xresources-dwm
xrdb ~/.config/xres/settings
xrdb -merge ~/.config/xresources-term
xrdb -merge ~/.config/xresources-dwm
notify "$fname"
