#!/bin/sh
# The commands to run when starting window managers
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"

# Shared terminal configs and colourscheme
[ -f "$XDG_CONFIG_HOME/xres/settings" ] && xrdb "$XDG_CONFIG_HOME/xres/settings"
[ -f "$XDG_CONFIG_HOME/xresources-term" ] && xrdb -merge "$XDG_CONFIG_HOME/xresources-term"
[ -f "$XDG_CONFIG_HOME/xresources-dwm" ] && xrdb -merge "$XDG_CONFIG_HOME/xresources-dwm"

# Set the background
if [ -f "$XDG_CONFIG_HOME/wallpaper" ]
then
    xwallpaper --zoom "$XDG_CONFIG_HOME/wallpaper"
else
    xsetroot -solid #000000
fi

# Enable compositing
pidof -x picom > /dev/null || picom &

# Custom X event functions
xbindkeys --file "$XDG_CONFIG_HOME/xres/xbindkeysrc"

# Automatically hide mouse cursor when unused
pidof -x unclutter > /dev/null || unclutter &

# Synchronize X server clipboard and cutbuffer
pidof -x autocutsel > /dev/null && pkill -x autocutsel
autocutsel -s CLIPBOARD &

# Background notification daemon
pidof -x dunst > /dev/null || dunst &

# Configure screensaver and DPMS times (in seconds)
xset s 600                  # 10m
xset dpms 900 1200 1800     # 15m 20m 30m

# Configure lockscreen on screensaver
pidof -x xss-lock > /dev/null || xss-lock --ignore-sleep -- lockscreen-cmd &

# Enable left pointer cursor
xsetroot -cursor_name left_ptr

# Faster keyboard repeat rate like the linux tty -- the configuration 
# file is under "$XDG_CONFIG_HOME/xautocfg.cfg"
xautocfg &

# Disable keyboard autorepeat except for specific keys
~/.local/scripts/configure-autorepeat &
