#!/bin/sh
# A script to unify X configuration between window managers
[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME="$HOME/.config"

# Shared terminal configs and colourscheme
[ -f "$XDG_CONFIG_HOME/xres/settings" ] && xrdb "$XDG_CONFIG_HOME/xres/settings"
[ -f "$XDG_CONFIG_HOME/xresources-term" ] && xrdb -merge "$XDG_CONFIG_HOME/xresources-term"
[ -f "$XDG_CONFIG_HOME/xresources-dwm" ] && xrdb -merge "$XDG_CONFIG_HOME/xresources-dwm"

# Set X background
xwallpaper --zoom "$XDG_CONFIG_HOME/wallpaper" || xsetroot -solid #000000

# Custom X event functions
xbindkeys --file "$XDG_CONFIG_HOME/xres/xbindkeysrc"

# Automatically hide mouse cursor when unused
unclutter &

# Synchronize PRIMARY and CLIPBOARD selections
autocutsel &

# Background notification daemon
dunst &

# Set colour temperature (use redshift-gtk instead for the widget)
# redshift -m randr -l -8.038958:-34.9574524 &

# Configure screensaver and DPMS times (in seconds)
xset s 600                  # 10m
xset dpms 900 1200 1800     # 15m 20m 30m

# Configure lockscreen on screensaver
xss-lock --ignore-sleep -- lockscreen-cmd &

# Enable left pointer cursor
xsetroot -cursor_name left_ptr

# Configure keyboard repeat rate
## 200ms delay before repeat, 40 repeats/sec
xset r rate 200 40

# Trackpad configuration
## Disable horizontal scroll
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Horizontal Scroll Enabled' 0

## Enable tap as left mouse button
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1

## Enable natural scrolling
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Natural Scrolling Enabled' 1
