#!/bin/sh
# A script to unify X configuration between window managers
[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME="$HOME/.config"

# Shared terminal configs and colourscheme
[ -f "$XDG_CONFIG_HOME/xres/settings" ] && xrdb "$XDG_CONFIG_HOME/xres/settings"
[ -f "$XDG_CONFIG_HOME/xresources-term" ] && xrdb -merge "$XDG_CONFIG_HOME/xresources-term"
[ -f "$XDG_CONFIG_HOME/xresources-dwm" ] && xrdb -merge "$XDG_CONFIG_HOME/xresources-dwm"

# Set X background
if [ -f "$XDG_CONFIG_HOME/wallpaper" ]
then
    xwallpaper --zoom "$XDG_CONFIG_HOME/wallpaper"
else
    xsetroot -solid #000000
fi

# Custom X event functions
xbindkeys --file "$XDG_CONFIG_HOME/xres/xbindkeysrc"

# Automatically hide mouse cursor when unused
pidof -x unclutter > /dev/null || unclutter &

# Synchronize PRIMARY and CLIPBOARD selections
pidof -x autocutsel > /dev/null && pkill -x autocutsel
autocutsel -s CLIPBOARD &
autocutsel -s PRIMARY &

# Background notification daemon
pidof -x dunst > /dev/null || dunst &

# Configure screensaver and DPMS times (in seconds)
xset s 600                  # 10m
xset dpms 900 1200 1800     # 15m 20m 30m

# Configure lockscreen on screensaver
pidof -x xss-lock > /dev/null || xss-lock --ignore-sleep -- lockscreen-cmd &

# Enable left pointer cursor
xsetroot -cursor_name left_ptr

# Configure keyboard repeat rate
## 200ms delay before repeat, 40 repeats/sec
xset r rate 200 40

# Trackpad configuration
## Disable horizontal scroll
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Horizontal Scroll Enabled' 0

## Enable tap as left mouse button
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1

## Enable natural scrolling
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Natural Scrolling Enabled' 1
