#!/bin/sh
# A unified menu for various configuration script selection
[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME="$HOME/.config"
[ -z "$XDG_DATA_HOME" ] && XDG_DATA_HOME="$HOME/.local/share"
SCRIPTS_HOME="$HOME/.local/bin"

OPTIONS="Aliases
Environment variables
Autostart configs
bash
bash aliases
zsh
zsh aliases
bspwm
sxhkd
sxiv
polybar
nvim
nvim plugins
doom emacs
doom emacs plugins
tmux
xinit
xresources
dunst
zathura
X colourscheme
Menu options"

option=$(echo "$OPTIONS" | dmenu_xres 'Which config to edit?')
case "$option" in
    'Aliases')
        xdg-open "$XDG_CONFIG_HOME/shells/aliases";;
    'Environment variables')
        xdg-open "$XDG_CONFIG_HOME/shells/environment";;
    'Autostart configs')
        xdg-open "$SCRIPTS_HOME/autostart-config";;
    'bash')
        xdg-open "$HOME/.bashrc";;
    'bash aliases')
        xdg-open "$XDG_CONFIG_HOME/shells/bash_aliases";;
    'zsh')
        xdg-open "$HOME/.zshrc";;
    'zsh aliases')
        xdg-open "$XDG_CONFIG_HOME/shells/zsh_aliases";;
    'bspwm')
        xdg-open "$XDG_CONFIG_HOME/bspwm/bspwmrc";;
    'sxhkd')
        xdg-open "$XDG_CONFIG_HOME/sxhkd/sxhkdrc";;
    'sxiv')
        xdg-open "$XDG_CONFIG_HOME/sxiv/exec/key-handler";;
    'polybar')
        xdg-open "$XDG_CONFIG_HOME/polybar/config";;
    'nvim')
        xdg-open "$XDG_CONFIG_HOME/nvim/init.vim";;
    'nvim plugins')
        xdg-open "$XDG_CONFIG_HOME/nvim/plug.vim";;
    'doom emacs')
        xdg-open "$HOME/.doom.d/config.el";;
    'doom emacs plugins')
        xdg-open "$HOME/.doom.d/init.el";;
    'tmux')
        xdg-open "$HOME/.tmux.conf";;
    'xinit')
        xdg-open "$HOME/.xinitrc";;
    'xresources')
        xdg-open "$XDG_CONFIG_HOME/xres/settings";;
    'dunst')
        xdg-open "$XDG_CONFIG_HOME/dunst/dunstrc";;
    'zathura')
        xdg-open "$XDG_CONFIG_HOME/zathura/zathurarc";;
    'X colourscheme')
        xdg-open "$SCRIPTS_HOME/setxtheme";;
    'Menu options')
        xdg-open "$SCRIPTS_HOME/edit-configs";;
    *)
        echo 'Error: Invalid option -- Doing nothing.';;
esac
