#!/bin/sh
# We'll be using this file to store the configuration that are specific to a
# system (e.g.: trackpad and keyboard configuration).

# TRACKPAD CONFIGURATION
## Disable horizontal scroll
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Horizontal Scroll Enabled' 0

## Enable tap as left mouse button
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1

## Enable natural scrolling
xinput --set-prop 'ETPS/2 Elantech Touchpad' 'libinput Natural Scrolling Enabled' 1

# KEYBOARD CONFIGURATION (XORG SESSIONS)
# More information on Arch's wiki:
#   https://wiki.archlinux.org/title/Xorg/Keyboard_configuration
#
# For an overview of the options used by Xorg, see:
#   `$ man 7 xkeyboard-config`

## Configuring this notebook's built-in keyboard
setxkbmap -device 15 -layout br

## Configuring USB keyboard with US International layout with AltGr dead key
setxkbmap -device 10 -layout 'us(altgr-intl)'
