#!/bin/bash
# A simple dmenu script to lock/close the WM or to shutdown.
# Usage:
#   manage_session
OPTIONS='Lock screen
Toggle screensaver
Close BSPWM
Reboot
Power-off'

option=$(echo "$OPTIONS" | dmenu_xres 'What now, chief?')
case "$option" in
    'Lock screen')
        lockscreen-cmd;;
    'Close BSPWM')
        pkill -x polybar; bspc quit;;
    'Reboot')
        reboot;;
    'Power-off')
        poweroff;;
esac
