#!/bin/sh
# Swallow the terminal window after xdg-open'ing the argument file
# This is a basic version of the 'devour' script:
#   https://github.com/salman-abedin/devour
#
# Usage:
#   swallow-open FILE
#
# Example:
#   swallow-open document.pdf
#
WINDOW_ID="$(xdo id)"
xdo hide
xdg-open "$@" > /dev/null 2>&1 
xdo show "$WINDOW_ID"
