#!/bin/bash

option=$(echo -e 'aliases\nenvironment variables\nbash\nbash aliases\nfish\nfish aliases\nbspwm\nsxhkd\npolybar\ntmux\nnvim\nranger' | dmenu -i $@ -p 'Which config to edit?')

case "$option" in
    'aliases')
        urxvtc -e $EDITOR ~/.shared_aliases;;
    'environment variables')
        urxvtc -e $EDITOR ~/.environment;;
    'bash')
        urxvtc -e $EDITOR ~/.bashrc;;
    'bash aliases')
        urxvtc -e $EDITOR ~/.bash_aliases;;
    'fish')
        urxvtc -e $EDITOR ~/.config/fish/config.fish;;
    'fish aliases')
        urxvtc -e $EDITOR ~/.config/fish/aliases.fish;;
    'bspwm')
        urxvtc -e $EDITOR ~/.config/bspwm/bspwmrc;;
    'sxhkd')
        urxvtc -e $EDITOR ~/.config/sxhkd/sxhkdrc;;
    'polybar')
        urxvtc -e $EDITOR ~/.config/polybar/config;;
    'tmux')
        urxvtc -e $EDITOR ~/.tmux.conf;;
    'nvim')
        urxvtc -e $EDITOR ~/.config/nvim/init.vim;;
    'Ranger')
        urxvtc -e $EDITOR ~/.config/ranger/rc.conf;;
esac

