#!/bin/bash

OPTIONS="Aliases
Environment variables
bash
bash aliases
fish
fish aliases
bspwm
sxhkd
sxiv
polybar
tmux
nvim
ranger
edit-menu"

option=$(echo -e "$OPTIONS" | dmenu -i $@ -p 'Which config to edit?')

case "$option" in
    'Aliases')
        urxvtc -e $EDITOR ~/.shared_aliases;;
    'Environment variables')
        urxvtc -e $EDITOR ~/.environment;;
    'bash')
        urxvtc -e $EDITOR ~/.bashrc;;
    'bash aliases')
        urxvtc -e $EDITOR ~/.bash_aliases;;
    'fish')
        urxvtc -e $EDITOR ~/.config/fish/config.fish;;
    'fish aliases')
        urxvtc -e $EDITOR ~/.config/fish/aliases.fish;;
    'bspwm')
        urxvtc -e $EDITOR ~/.config/bspwm/bspwmrc;;
    'sxhkd')
        urxvtc -e $EDITOR ~/.config/sxhkd/sxhkdrc;;
    'sxiv')
        urxvtc -e $EDITOR ~/.config/sxiv/exec/key-handler;;
    'polybar')
        urxvtc -e $EDITOR ~/.config/polybar/config;;
    'tmux')
        urxvtc -e $EDITOR ~/.tmux.conf;;
    'nvim')
        urxvtc -e $EDITOR ~/.config/nvim/init.vim;;
    'ranger')
        urxvtc -e $EDITOR ~/.config/ranger/rc.conf;;
    'edit-menu')
        urxvtc -e $EDITOR ~/.local/share/custom-scripts/edit_configs;;
esac

