#!/bin/bash
# A simple dmenu script to lock/close the WM or to shutdown.
# Usage: manage_session [DMENU_OPTIONS]

option=$(echo -e 'Cancel\nLock Screen\nExit Window Manager\nReboot\nShut Down' | dmenu -i $@ -p 'What now chief?')

case "$option" in
	'Lock Screen')
        slock;;
    'Exit Window Manager')
        pkill -x polybar; bspc quit;;
    'Reboot')
        reboot;;
    'Shut Down')
        poweroff;;
esac

