#!/usr/bin/env python3
"""For those important decisions..."""
import argparse
import random


DEFAULT_THRESHOLD = 0.5

def __probability(x):
    x = float(x)

    if not (0 <= x <= 1):
        raise argparse.ArgumentTypeError(f'\'{x}\' is outside of the [0,1] range')

    return x


def main(threshold):
    response = 'default'

    if random.uniform(0,1) < threshold:
        response = 'Yes'
    else:
        response = 'No'

    print(response)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    group = parser.add_mutually_exclusive_group()
    group.add_argument('-p',type=__probability, help='The probability of saying \'Yes\'', metavar='0 <= p <= 1')
    group.add_argument('-q',type=__probability, help='The probability of saying \'No\'', metavar='0 <= q <= 1')

    args = parser.parse_args()

    threshold = DEFAULT_THRESHOLD
    if args.p is not None:
        threshold = args.p
    elif args.q is not None:
        threshold = 1 - args.q

    main(threshold)

