#!/bin/sh
# nnn plugin -- Open the file using xdg-open and swallow the window
#
# Args:
#   $1: Hovered filename
#   $2: Absolute path to the current directory (not used)

if [ -f "$1" ]
then
    swallow-open "$1"
fi
