#!/bin/sh
# Here you get BSPWM's settings
# Workspace labels
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Frame padding
bspc config top_padding         0
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

# Borders and gaps
bspc config border_width        3
bspc config window_gap          3
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

# A red and black colorscheme based on RUINER
bspc config normal_border_color     "#770005"
bspc config focused_border_color    "#DC122A"
bspc config presel_feedback_color   "#DDFAFA"

# These were here by default
bspc rule -a 'mplayer2' state=floating
bspc rule -a 'Screenkey' manage=off

# Panels can be focused by left clicking
bspc config click_to_focus button1
bspc config swallow_first_click true

# Workspace assignment
bspc rule -a 'VirtualBox Manager' desktop='^8'
bspc rule -a 'Gimp-2.10' desktop='^9'
bspc rule -a 'Gimp' desktop='^9'
bspc rule -a 'Inkscape' desktop='^9'
bspc rule -a 'KeePassXC' desktop='^10'
