#! /bin/sh
#
# version 0.9.12

# initialize the hotkey daemon and status bar
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar bsp &

# the number and the labels of available desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9

# frame padding
# bspc config top_padding         0
# bspc config bottom_padding      0
# bspc config left_padding        0
# bspc config right_padding       0

# borders and gaps
bspc config border_width        2
bspc config window_gap          2

bspc config split_ratio         0.5
# bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

# mouse settings
# bspc config swallow_first_click true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
