#!/bin/bash
# Input devices configuration through synaptics driver

# Enable Natural Scrolling (negative values)
synclient VertScrollDelta=-80
synclient HorizScrollDelta=-80

# Disable edge scrolling both vertically and horizontally
synclient VertEdgeScroll=0
synclient HorizEdgeScroll=0

# Disable horizontal two-finger scroll
synclient HorizTwoFingerScroll=0

# Disable Right-Top and Right-Bottom corner button
synclient RTCornerButton=0
synclient RBCornerButton=0

# Disable two and three finger tracking for LMB and RMB
synclient TapButton2=0
synclient TapButton3=0

# Disable Coasting speed (i.e. inertia)
synclient CoastingSpeed=0

# Adjusts trackpad tap time to a shorter value
synclient MaxTapTime=90

# Sets the cursor movement speed
synclient MinSpeed=1
synclient MaxSpeed=2

