#!/bin/sh
# Here you get BSPWM's settings
# Workspace labels
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Frame padding
bspc config top_padding         0
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

# Borders and gaps
bspc config border_width        3
bspc config window_gap          5
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# A red and black colorscheme based on RUINER
bspc config normal_border_color     "#880005"
bspc config focused_border_color    "#DC122A"
bspc config presel_feedback_color   "#DDFAFA"

# These were here by default
bspc rule -a 'mplayer2' state=floating
bspc rule -a 'Screenkey' manage=off

# Panels can be focused by left clicking
bspc config click_to_focus button1
bspc config swallow_first_click true

# Workspace assignment
## Internet browsers
bspc rule -a 'firefox' desktop='^1'
bspc rule -a 'Opera' desktop='^1'
bspc rule -a 'qutebrowser' desktop='^1'
bspc rule -a 'Brave-browser' desktop='^1'
bspc rule -a 'Tor Browser' desktop='^1'

## Terminal emulators
bspc rule -a 'URxvt' desktop='^2'
bspc rule -a 'UXTerm' desktop='^2'
bspc rule -a 'XTerm' desktop='^2'
bspc rule -a 'cool-retro-term' desktop='^2'

## Some other stuff
bspc rule -a 'code-oss' desktop='^3'
bspc rule -a 'Zathura' state=tiled
bspc rule -a 'VirtualBox Manager' desktop='^8'
bspc rule -a 'Gimp-2.10' desktop='^9'
bspc rule -a 'Gimp' desktop='^9'
bspc rule -a 'Inkscape' desktop='^9'
bspc rule -a 'Keepassx2' desktop='^10'
bspc rule -a 'RStudio' desktop='^4'
