#!/bin/bash
# Here you get BSPWM's settings, this script uses
#
#   * sxhkd:    The hotkey event daemon;
#   * polybar:  The status bar;
#   * feh:      Image viewer -- set background image.

sxhkd &
polybar statusbar &

# Workspace labels
bspc monitor -d I II III IV V VI VII VIII IX X

# Frame padding
bspc config top_padding         0
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

# Borders and gaps
bspc config border_width        3
bspc config window_gap          6
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# RUINER-based red and black colorscheme
bspc config normal_border_color     "#880005"
bspc config focused_border_color    "#DC122A"
bspc config presel_feedback_color   "#DDFAFA"

# These were here by default
bspc rule -a 'mplayer2' state=floating
bspc rule -a 'Screenkey' manage=off

# Click on panel to focus
bspc config click_to_focus button1

# Workspace assignment
## Internet browsers
bspc rule -a 'Firefox' desktop='^1'
bspc rule -a 'Vivaldi-stable' desktop='^1'
bspc rule -a 'Opera' desktop='^1'
bspc rule -a 'qutebrowser' desktop='^1'
bspc rule -a 'Surf' state=tiled

## Terminal emulators
bspc rule -a 'URxvt' desktop='^2'
bspc rule -a 'UXTerm' desktop='^2'
bspc rule -a 'XTerm' desktop='^2'
bspc rule -a 'cool-retro-term' desktop='^2'

## Some other stuff
bspc rule -a 'Code' desktop='^4'
bspc rule -a 'Zathura' state=tiled
bspc rule -a 'VirtualBox Manager' desktop='^8'
bspc rule -a 'Gimp' desktop='^9'
bspc rule -a 'Inkscape' desktop='^9'
bspc rule -a 'discord' desktop='^9'
bspc rule -a 'Keepassx2' desktop='^10'

# Set background image
feh --bg-fill "$HOME/Pictures/wallpapers/no-file-large-bright.png"

# Enable left pointer cursor
xsetroot -cursor_name left_ptr

# Custom keyboard and trackpad configuration
source "$HOME/.config/input-confs/keyboard-confs"
source "$HOME/.config/input-confs/libinput-confs"

