;; -*- lexical-binding: t; -*-
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-blinks 0)
 '(column-number-mode t)
 '(confirm-kill-emacs 'yes-or-no-p)
 '(context-menu-mode t)
 '(cursor-in-non-selected-windows 'hollow)
 '(cursor-type 'bar)
 '(custom-enabled-themes nil)
 '(delete-by-moving-to-trash t)
 '(delete-selection-mode t)
 '(display-line-numbers-type 'absolute)
 '(display-line-numbers-width 3)
 '(ediff-keep-variants nil)
 '(ediff-show-clashes-only t)
 '(ediff-split-window-function 'split-window-horizontally)
 '(ediff-window-setup-function 'ediff-setup-windows-plain)
 '(editorconfig-mode t)
 '(electric-pair-mode t)
 '(fill-column 100)
 '(frame-resize-pixelwise t)
 '(global-auto-revert-mode t)
 '(global-display-fill-column-indicator-mode t)
 '(global-display-line-numbers-mode t)
 '(global-hl-line-mode t)
 '(global-prettify-symbols-mode t)
 '(global-so-long-mode t)
 '(global-whitespace-mode t)
 '(help-window-select t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-scratch-message
   ";;; Scratch area for Emacs lisp\12;; * movement\12;; `backward-sexp' (C-M-b)\12;; `forward-sexp' (C-M-f)\12;; `forward-list' (C-M-n)\12;; `backward-list' (C-M-p)\12;;\12;; * selection\12;; `mark-defun' (C-M-h)\12;; `mark-sexp' (C-M-SPC)\12;;\12;; * evaluation\12;; `eval-buffer' (C-c e)\12;; `eval-last-sexp' (C-x C-e)\12;; `eval-defun' (C-M-x)\12;; `eval-print-last-sexp' (C-j)\12;; `eval-expression' (M-:)\12;; `eval-region'\12")
 '(kill-ring-deindent-mode t)
 '(menu-bar-mode t)
 '(mode-line-collapse-minor-modes t)
 '(mode-line-compact t)
 '(mode-line-position-column-line-format '(" (%l,%C)"))
 '(mouse-wheel-progressive-speed nil)
 '(org-M-RET-may-split-line '((default)))
 '(org-startup-folded 'content)
 '(package-selected-packages nil)
 '(repeat-mode t)
 '(require-final-newline t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 100)
 '(scroll-margin 10)
 '(select-active-regions nil)
 '(tab-bar-mode t)
 '(tab-bar-show 1)
 '(tab-bar-tab-hints t)
 '(tab-width 4)
 '(tool-bar-mode nil)
 '(use-short-answers t)
 '(vc-follow-symlinks nil)
 '(which-key-idle-delay 0.5)
 '(which-key-mode t)
 '(whitespace-style
   '(face trailing tabs spaces newline missing-newline-at-eof empty indentation space-after-tab
          space-before-tab space-mark tab-mark newline-mark)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(italic ((t (:slant italic))))
 '(tab-bar ((t nil)))
 '(tab-bar-tab ((t (:background "gold1" :foreground "black" :box (:line-width (1 . 1) :style released-button)))))
 '(tab-bar-tab-inactive ((t nil)))
 '(whitespace-empty ((t (:inherit nil))))
 '(whitespace-line ((t nil)))
 '(whitespace-missing-newline-at-eof ((t nil)))
 '(whitespace-newline ((t (:foreground "gold" :weight bold))))
 '(whitespace-space ((t (:foreground "gold" :weight bold))))
 '(whitespace-tab ((t (:foreground "dodger blue" :weight bold)))))
