#!/bin/sh
# Keyboard shortcuts for sxiv
#
# Activate hotkey mode with CTRL+x then press one of the following options:
#   y: Copy current image name into X's selection
#   c: Copy selected images' names into X's selection
#   o: Open selected images with Gimp
#   w: Set current image as wallpaper

selection=false
open_files=false
fnames=''

copy_to_selection() {
    echo -n "$1" | xclip -selection clipboard
    echo -n "$1" | xclip -selection primary
}

notify() {
    pgrep -x dunst 1> /dev/null && dunstify "$@"
}

while read file
do
    case "$1" in
        "y")
            copy_to_selection "$file"
            notify 'Copied to clipboard' "$file";;
        "c")
            selection=true
            [ -z "$fnames" ] && fnames="$file" || fnames="$fnames $file";;
        "o")
            open_files=true
            [ -z "$fnames" ] && fnames="$file" || fnames="$fnames $file";;
        "w")
            ~/.local/scripts/setxbackground "$file";;
    esac
done

if [ "$selection" = true ]; then
    copy_to_selection "$fnames"
    notify 'Copied to selection' "$fnames"
elif [ "$open_files" = true ]; then
    gimp $fnames
fi
