# Put here your bash exclusive aliases

# Source python virtual environments
alias p3='source ~/.local/share/python/environments/p3h/bin/activate'
alias ml='source ~/.local/share/python/environments/mlh/bin/activate'
alias venv='source .venv/bin/activate'
